### ISSUE TITLE
在一家网吧跑，没执行起来

### ISSUE THREAD

**Issue by QisFj** [misaka10843/genshin-server-switching#3]
用 powershell 打开：
```
PS C:\360极速浏览器下载> .\genshin-server-switching_Win_x64.exe
欢迎使用原神快速换服程序qwq

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/misaka10843/genshin-server-switching@2.0/ver.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 80, in <module>
  File "main.py", line 11, in getversion
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/misaka10843/genshin-server-switching@2.0/ver.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[10076] Failed to execute script 'main' due to unhandled exception!
```

看起来是过去 ver.json 的时候出现了点问题，ping 了一下 cdn.jsdelivr.net 和 wget 了一下这个 json，看起来是没有问题的：
```
PS C:\360极速浏览器下载> ping cdn.jsdelivr.net -n 10

正在 Ping jsdelivr.map.fastly.net [151.101.109.229] 具有 32 字节的数据:
来自 151.101.109.229 的回复: 字节=32 时间=98ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=99ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=99ms TTL=52
请求超时。
来自 151.101.109.229 的回复: 字节=32 时间=98ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=99ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=99ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=99ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=98ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=98ms TTL=52

151.101.109.229 的 Ping 统计信息:
    数据包: 已发送 = 10，已接收 = 9，丢失 = 1 (10% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 98ms，最长 = 99ms，平均 = 98ms
PS C:\360极速浏览器下载> wget cdn.jsdelivr.net/gh/misaka10843/genshin-server-switching@2.0/ver.json


StatusCode        : 200
StatusDescription : OK
Content           : {
                    "game_version":"2.1.0",
                    "mihoyo_channel":"1",
                    "mihoyo_sub_channel":"1",
                    "mihoyo_cps":"mihoyo",
                    "bili_channel":"14",
                    "bili_sub_channel":"0",
                    "bili_cps":"bilibili"
                    }

RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Connection: keep-alive
                    Access-Control-Allow-Origin: *
                    Access-Control-Expose-Headers: *
                    Timing-Allow-Origin: *
                    Cross-Origin-Resource-Policy: cross-origi...
Forms             : {}
Headers           : {[Transfer-Encoding, chunked], [Connection, keep-alive], [Access-Control-Allow-Origin, *], [Access-Control-E
                    xpose-Headers, *]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 166
```

**Comment by misaka10843** [comment]
（其实是jsdelivr时常抽风wwww

最近会修复一下链接，尽量同步到gitee后直接将jsdelivr改成gitee

但是最近似乎是米忽悠特地不想让玩家两服一端，所以最近可以说功能已经失效了qwq

虽然可以添加更多文件来修复此bug，但是也不是长久之计🤣

**Comment by misaka10843** [comment]
> （其实是jsdelivr时常抽风wwww
> 
> 最近会修复一下链接，尽量同步到gitee后直接将jsdelivr改成gitee
> 
> 但是最近似乎是米忽悠特地不想让玩家两服一端，所以最近可以说功能已经失效了qwq
> 
> 虽然可以添加更多文件来修复此bug，但是也不是长久之计🤣

已经找到问题，因为在编译后因为jsdelivr不稳定性所以替换成了gitee，但是因为没有重新编译导致最新的版本是使用的jsdelivr

然后因为是更新了2.5，所以也准备将原先直接替换的文件写个备份，以防止中途任何一个文件下载失败导致无法启动

**Comment by misaka10843** [comment]
如还有此类问题请重新打开此issue并且附带错误输出，感谢支持qwq
